on: {}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
